### ISSUE TITLE
json - label

### ISSUE THREAD

**Issue by marcin-filipiak** [kakd20061/Esp32PublicFiles#1]
{
          "type": "label",
          "label": "temperatura",
          "name": "temperature",
          "value": "25C"
}

Proponuję usunąć "label":"temperatura".  Zadaniem typu label jest wyświetlanie samego tekstu, więc wystarczy postać:

{
          "type": "label",
          "name": "temperature",
          "value": "temperatura 25C"
}

**Comment by kakd20061** [comment]
sensowne
