### ISSUE TITLE
json - switch

### ISSUE THREAD

**Issue by marcin-filipiak** [kakd20061/Esp32PublicFiles#2]
{
          "type": "switch",
          "label": "Ogrzewanie",
          "name": "heating",
          "set": false,
          "autosend": true
}

Typ "switch" jest trochę problematyczny z nazwą (instrukcja "switch" w c++). 
Proponuję zamienić na np. binswitch (od binarny przycisk), czyli do formatu:

{
          "type": "binswitch",
          "label": "Ogrzewanie",
          "name": "heating",
          "set": false,
          "autosend": true
}

**Comment by kakd20061** [comment]
Okej, zmienię to jutro
